/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FailedJobsService } from "../failedJobs.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FailedJobsCreateInput } from "./FailedJobsCreateInput";
import { FailedJobs } from "./FailedJobs";
import { FailedJobsFindManyArgs } from "./FailedJobsFindManyArgs";
import { FailedJobsWhereUniqueInput } from "./FailedJobsWhereUniqueInput";
import { FailedJobsUpdateInput } from "./FailedJobsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FailedJobsControllerBase {
  constructor(
    protected readonly service: FailedJobsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FailedJobs })
  @nestAccessControl.UseRoles({
    resource: "FailedJobs",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFailedJobs(
    @common.Body() data: FailedJobsCreateInput
  ): Promise<FailedJobs> {
    return await this.service.createFailedJobs({
      data: data,
      select: {
        connection: true,
        createdAt: true,
        exception: true,
        failedAt: true,
        id: true,
        payload: true,
        queue: true,
        updatedAt: true,
        uuid: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FailedJobs] })
  @ApiNestedQuery(FailedJobsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FailedJobs",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async failedJobsItems(@common.Req() request: Request): Promise<FailedJobs[]> {
    const args = plainToClass(FailedJobsFindManyArgs, request.query);
    return this.service.failedJobsItems({
      ...args,
      select: {
        connection: true,
        createdAt: true,
        exception: true,
        failedAt: true,
        id: true,
        payload: true,
        queue: true,
        updatedAt: true,
        uuid: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FailedJobs })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FailedJobs",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async failedJobs(
    @common.Param() params: FailedJobsWhereUniqueInput
  ): Promise<FailedJobs | null> {
    const result = await this.service.failedJobs({
      where: params,
      select: {
        connection: true,
        createdAt: true,
        exception: true,
        failedAt: true,
        id: true,
        payload: true,
        queue: true,
        updatedAt: true,
        uuid: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FailedJobs })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FailedJobs",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFailedJobs(
    @common.Param() params: FailedJobsWhereUniqueInput,
    @common.Body() data: FailedJobsUpdateInput
  ): Promise<FailedJobs | null> {
    try {
      return await this.service.updateFailedJobs({
        where: params,
        data: data,
        select: {
          connection: true,
          createdAt: true,
          exception: true,
          failedAt: true,
          id: true,
          payload: true,
          queue: true,
          updatedAt: true,
          uuid: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FailedJobs })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FailedJobs",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFailedJobs(
    @common.Param() params: FailedJobsWhereUniqueInput
  ): Promise<FailedJobs | null> {
    try {
      return await this.service.deleteFailedJobs({
        where: params,
        select: {
          connection: true,
          createdAt: true,
          exception: true,
          failedAt: true,
          id: true,
          payload: true,
          queue: true,
          updatedAt: true,
          uuid: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
